# Generated by Django 3.0.2 on 2020-02-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=150, verbose_name='Linha 1')),
                ('line_two', models.CharField(blank=True, max_length=150, null=True, verbose_name='Linha 2')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('nation', models.CharField(max_length=50, verbose_name='País')),
                ('lat', models.IntegerField(blank=True, null=True, verbose_name='Latitude')),
                ('long', models.IntegerField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
    ]
