# Generated by Django 3.0.2 on 2020-01-24 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTourist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField()),
                ('time_func', models.CharField(max_length=200, verbose_name='Horário de Funcionamento')),
                ('date_register', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Recurso Turistíco',
                'verbose_name_plural': 'Recursos Turistícos',
            },
        ),
    ]
