# Generated by Django 3.0.2 on 2020-01-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tourist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetourist',
            name='date_register',
            field=models.DateField(auto_now_add=True),
        ),
    ]
