# Generated by Django 3.0.2 on 2020-01-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontosTuristicos',
            new_name='TouristPoint',
        ),
    ]
