# Generated by Django 3.0.2 on 2020-01-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200124_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='touristpoint',
            options={'verbose_name': 'Ponto Turistico', 'verbose_name_plural': 'Pontos Turisticos'},
        ),
        migrations.AlterField(
            model_name='touristpoint',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
    ]
