# Generated by Django 3.0.2 on 2020-01-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tourist', '0001_initial'),
        ('core', '0003_auto_20200124_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='resource_tourist',
            field=models.ManyToManyField(to='resource_tourist.ResourceTourist'),
        ),
    ]
