# Generated by Django 3.0.2 on 2020-01-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_tourist', '0002_auto_20200124_1844'),
        ('comment', '0001_initial'),
        ('core', '0006_auto_20200124_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristpoint',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='touristpoint',
            name='resource_tourists',
            field=models.ManyToManyField(blank=True, to='resource_tourist.ResourceTourist'),
        ),
    ]
