# Generated by Django 3.0.2 on 2020-02-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('core', '0007_auto_20200124_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='review',
            field=models.ManyToManyField(blank=True, to='reviews.Review'),
        ),
    ]
