# Generated by Django 3.0.2 on 2020-02-01 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('core', '0008_touristpoint_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='location.Location'),
            preserve_default=False,
        ),
    ]
