# Generated by Django 3.0.2 on 2020-02-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_touristpoint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristpoint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_point'),
        ),
    ]
